In [ ]:
%%sql

-- SELECT * from all_trading_days limit 10
/* 
select a.*,b.total_market_cap
from cn_stock_real_bar1d a
inner join cn_stock_valuation b on a.date = b.date and a.instrument = b.instrument
where  a.date = '2026-02-12' and b.total_market_cap < 10000000000
order by b.total_market_cap DESC

select *
from  cn_stock_real_bar1d 
where date between '2026-01-01'  and '2026-02-12' and instrument ='000001.SZ'


select a.date,a.instrument ,a.name,a.adjust_factor,a.close,b.instrument,b.date,b.sma_60, b.sma_5,b.ema_60  ,b.*
from cn_stock_real_bar1d  a
inner join cn_stock_factors_ta b on a.instrument = b.instrument and a.date = b.date 
where a.instrument = '000001.SZ' and b.sma_5 is not null  and a.date >'2026-01-01'
--and a.close > b.sma_60 and a.pre_close < b.sma_60
order by a.instrument  asc
select * from cn_stock_factors_ta where instrument = '000001.SZ'


select * from cn_stock_real_bar1d where instrument = '000001.SZ' and date >'2026-01-01'  order by date ASC        
*/

select * 
from cn_stock_instruments where data = '2026-04-17'

In [1]:
%%sql
CREATE  TABLE TEMP AS
select a.date,
       a.instrument,
       a.name,
       a.adjust_factor,
       a.pre_close,
       a.change_ratio,
       a.close,
       a.volume,
       c.pe_ttm,
       c.pe_leading,
       ROUND(b.sma_5 / a.adjust_factor, 2) as sma_5,
       ROUND(b.sma_60/a.adjust_factor,2) as sma_60
from cn_stock_real_bar1d  a
inner join cn_stock_factors_ta b on a.instrument = b.instrument and a.date = b.date 
inner join cn_stock_valuation c on a.instrument = c.instrument and a.date = c.date 
where a.date >'2025-01-01';
 
/*
with temp30 as 
    select a.instrument,
           max(a.sma_60),
           min(a.sma_60),
           max(a.volume),
           min(a.volume)
    from TEMP a 
    where a.date between '2026-01-01' and '2026-02-25' ;
    */


SELECT  a.date,
        a.instrument,
        a.name,
        a.close,
        a.change_ratio*100,
        a.volume,
        a.sma_5,
        a.sma_60,
        a.pe_ttm
FROM TEMP A 
WHERE A.DATE = '2026-03-04'
and a.close < a.sma_60*0.8 
-- and a.close > a.sma_60*0.8
and a.pe_ttm > 0 
and a.pe_ttm <100 
order by a.change_ratio desc ;

/*
低于60日均线 80% and 近一个季度利润在增长 
*/

from bigmodule import M

# <aistudiograph>
# </aistudiograph>

ParserException: Parser Error: syntax error at or near "M"

In [26]:
SELECT * FROM TEMP

SyntaxError: invalid syntax (1950192966.py, line 1)

In [5]:
%%sql
/*
select *
from  cn_stock_real_bar1d 
where date between '2026-01-01'  and '2026-02-12' and instrument ='000001.SZ'

select * from cn_stock_factors_ta
where date between '2026-01-01' and '2026-02-12' and instrument = '000001.SZ' limit 100

select a.date,a.instrument ,a.name,a.adjust_factor,a.close,ROUND(b.sma_5 / a.adjust_factor, 2) as sma_5 , ROUND(b.sma_60/a.adjust_factor,2) as sma_60 
from cn_stock_real_bar1d  a
inner join cn_stock_factors_ta b on a.instrument = b.instrument and a.date = b.date 
where a.instrument = '000001.SZ' and a.date >'2025-01-01'
--and a.close > b.sma_60 and a.pre_close < b.sma_60
order by a.date  asc
*/

WITH t AS (
select a.date,
       a.instrument,
       a.name,
       a.adjust_factor,
       a.pre_close,
       a.close,
       ROUND(b.sma_5 / a.adjust_factor, 2) as sma_5,
       ROUND(b.sma_60/a.adjust_factor,2) as sma_60
from cn_stock_real_bar1d  a
inner join cn_stock_factors_ta b on a.instrument = b.instrument and a.date = b.date 
where a.date >'2025-01-01'
order by a.date  asc
)

select * from t  where  date = '2026-02-26'

┌─────────────────────┬────────────┬──────────┬────────────────────┬───────────┬────────┬────────┬────────┐
│        date         │ instrument │   name   │   adjust_factor    │ pre_close │ close  │ sma_5  │ sma_60 │
│    timestamp_ns     │  varchar   │ varchar  │       double       │  double   │ double │ double │ double │
├─────────────────────┼────────────┼──────────┼────────────────────┼───────────┼────────┼────────┼────────┤
│ 2026-02-26 00:00:00 │ 000001.SZ  │ 平安银行 │ 134.57976911799145 │     10.86 │  10.87 │   NULL │   NULL │
│ 2026-02-26 00:00:00 │ 000002.SZ  │ 万  科Ａ │ 181.70378216936547 │       5.0 │   4.82 │   NULL │   NULL │
│ 2026-02-26 00:00:00 │ 000004.SZ  │ *ST国华  │  4.063861846923828 │      7.54 │   7.16 │   NULL │   NULL │
│ 2026-02-26 00:00:00 │ 000006.SZ  │ 深振业Ａ │  39.73967361450195 │      9.68 │   9.32 │   NULL │   NULL │
│ 2026-02-26 00:00:00 │ 000007.SZ  │ 全新好   │  8.283528327941895 │     12.61 │  13.16 │   NULL │   NULL │
│ 2026-02-26 00:00:00 │ 000008.SZ  │ 神州高铁 │ 22.408292770385742 │      3.05 │   3.02 │   NULL │   NULL │
│ 2026-02-26 00:00:00 │ 000009.SZ  │ 中国宝安 │  9.005208088336353 │      9.59 │    9.5 │   NULL │   NULL │
│ 2026-02-26 00:00:00 │ 000010.SZ  │ 美丽生态 │ 10.774548530578613 │       3.7 │   4.07 │   NULL │   NULL │
│ 2026-02-26 00:00:00 │ 000011.SZ  │ 深物业A  │  4.410767615341475 │      9.25 │   8.91 │   NULL │   NULL │
│ 2026-02-26 00:00:00 │ 000012.SZ  │ 南  玻Ａ │ 30.345006051394282 │      5.18 │   5.04 │   NULL │   NULL │
│          ·          │     ·      │    ·     │          ·         │        ·  │     ·  │     ·  │     ·  │
│          ·          │     ·      │    ·     │          ·         │        ·  │     ·  │     ·  │     ·  │
│          ·          │     ·      │    ·     │          ·         │        ·  │     ·  │     ·  │     ·  │
│ 2026-02-26 00:00:00 │ 920964.BJ  │ 润农节水 │  2.217582458662233 │      6.99 │   7.03 │   NULL │   NULL │
│ 2026-02-26 00:00:00 │ 920970.BJ  │ 大禹生物 │ 2.1728720664978027 │      8.08 │   8.06 │   NULL │   NULL │
│ 2026-02-26 00:00:00 │ 920971.BJ  │ 天马新材 │  2.609441019331289 │      31.7 │  31.22 │   NULL │   NULL │
│ 2026-02-26 00:00:00 │ 920974.BJ  │ 凯大催化 │ 2.2205135293037137 │       8.8 │    8.7 │   NULL │   NULL │
│ 2026-02-26 00:00:00 │ 920976.BJ  │ 视声智能 │  2.320673970704945 │     32.44 │  31.43 │   NULL │   NULL │
│ 2026-02-26 00:00:00 │ 920978.BJ  │ 开特股份 │ 1.2886401623679884 │     30.84 │  30.49 │   NULL │   NULL │
│ 2026-02-26 00:00:00 │ 920981.BJ  │ 晶赛科技 │ 1.4342682847180337 │     32.75 │  33.81 │   NULL │   NULL │
│ 2026-02-26 00:00:00 │ 920982.BJ  │ 锦波生物 │  4.283133323195494 │    219.49 │ 218.99 │   NULL │   NULL │
│ 2026-02-26 00:00:00 │ 920985.BJ  │ 海泰新能 │ 1.6280360169613861 │      8.53 │    8.3 │   NULL │   NULL │
│ 2026-02-26 00:00:00 │ 920992.BJ  │ 中科美菱 │ 1.4931603899205967 │     16.73 │  16.69 │   NULL │   NULL │
├─────────────────────┴────────────┴──────────┴────────────────────┴───────────┴────────┴────────┴────────┤
│ 5471 rows (20 shown)                                                                          8 columns │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────┘

In [5]:

result = _.df()
result

,date,instrument,name,adjust_factor,pre_close,close,sma_5,sma_60
0,2025-01-02,000001.SZ,平安银行,127.784450,11.70,11.43,NaN,NaN
1,2025-01-02,000002.SZ,万 科Ａ,181.703782,7.26,7.11,NaN,NaN
2,2025-01-02,000004.SZ,国华网安,4.063862,13.84,14.18,NaN,NaN
3,2025-01-02,000006.SZ,深振业Ａ,39.739674,7.32,7.25,NaN,NaN
4,2025-01-02,000007.SZ,全新好,8.283528,7.03,7.02,NaN,NaN
...,...,...,...,...,...,...,...,...
1494240,2026-02-26,920978.BJ,开特股份,1.288640,30.84,30.49,30.40,34.35
1494241,2026-02-26,920981.BJ,晶赛科技,1.434268,32.75,33.81,32.56,33.16
1494242,2026-02-26,920982.BJ,锦波生物,4.283133,219.49,218.99,218.62,233.25
1494243,2026-02-26,920985.BJ,海泰新能,1.628036,8.53,8.30,8.53,8.06
1494244,2026-02-26,920992.BJ,中科美菱,1.493160,16.73,16.69,16.63,17.84

In [ ]:
#导入股票池
import pandas as pd

# 读取 GB2312 编码的 CSV 文件
df = pd.read_csv('/home/aiuser/work/我的文档/量化交易/股票池/股票池分析_20260213_20260213 .csv', encoding='gb2312')
print(df)

          热点日期   领域名称       股票代码    股票名称  股票得分  买入理由  买入建议  \
0   2026-02-13   军工装备  sh.601890    亚星锚链   NaN   NaN   NaN
1   2026-02-13   军工装备  sz.300719    安达维尔   NaN   NaN   NaN
2   2026-02-13   军工装备  sh.688563    航材股份   NaN   NaN   NaN
3   2026-02-13   军工装备  sz.300065     海兰信   NaN   NaN   NaN
4   2026-02-13   军工装备  sz.300589    江龙船艇   NaN   NaN   NaN
5   2026-02-13   军工装备  sh.600118    中国卫星   NaN   NaN   NaN
6   2026-02-13  半导体设备  sh.688409    富创精密   NaN   NaN   NaN
7   2026-02-13  半导体设备  sh.688702  盛科通信-U   NaN   NaN   NaN
8   2026-02-13  半导体设备  sh.688012    中微公司   NaN   NaN   NaN
9   2026-02-13  半导体设备  sz.002371    北方华创   NaN   NaN   NaN
10  2026-02-13  半导体设备  sh.688082    盛美上海   NaN   NaN   NaN
11  2026-02-13  半导体设备  sh.688072    拓荆科技   NaN   NaN   NaN
12  2026-02-13   存储芯片  sh.688525    佰维存储   NaN   NaN   NaN
13  2026-02-13   存储芯片  sh.688110    东芯股份   NaN   NaN   NaN
14  2026-02-13   存储芯片  sz.300223    北京君正   NaN   NaN   NaN
15  2026-02-13   存储芯片  sh.688008    澜起科技   NaN   NaN   NaN
16  2026-02-13   存储芯片  sh.603986    兆易创新   NaN   NaN   NaN
17  2026-02-13   存储芯片  sh.688766    普冉股份   NaN   NaN   NaN
18  2026-02-13   影视院线  sz.300251    光线传媒   NaN   NaN   NaN
19  2026-02-13   影视院线  sz.300182    捷成股份   NaN   NaN   NaN
20  2026-02-13   影视院线  sh.600977    中国电影   NaN   NaN   NaN
21  2026-02-13   影视院线  sh.603103    横店影视   NaN   NaN   NaN
22  2026-02-13   影视院线  sz.001330    博纳影业   NaN   NaN   NaN
23  2026-02-13   影视院线  sh.600088    中视传媒   NaN   NaN   NaN
24  2026-02-13   商业航天  sh.600118    中国卫星   NaN   NaN   NaN
25  2026-02-13   商业航天  sh.601698    中国卫通   NaN   NaN   NaN
26  2026-02-13   商业航天  sh.688270    臻镭科技   NaN   NaN   NaN
27  2026-02-13   商业航天  sz.300342    天银机电   NaN   NaN   NaN
28  2026-02-13   商业航天  sh.688523    航天环宇   NaN   NaN   NaN
29  2026-02-13   商业航天  sz.300045    华力创通   NaN   NaN   NaN
30  2026-02-13   智能座舱  sz.002920    德赛西威   NaN   NaN   NaN
31  2026-02-13   智能座舱  sh.688326    经纬恒润   NaN   NaN   NaN
32  2026-02-13   智能座舱  sz.300496    中科创达   NaN   NaN   NaN
33  2026-02-13   智能座舱  sh.688208    道通科技   NaN   NaN   NaN
34  2026-02-13   智能座舱  sz.002906    华阳集团   NaN   NaN   NaN
35  2026-02-13   智能座舱  sh.688787    海天瑞声   NaN   NaN   NaN
36  2026-02-13     造纸  sh.605007    五洲特纸   NaN   NaN   NaN
37  2026-02-13     造纸  sz.301469    恒达新材   NaN   NaN   NaN
38  2026-02-13     造纸  sh.600966    博汇纸业   NaN   NaN   NaN
39  2026-02-13     造纸  sh.600567    山鹰国际   NaN   NaN   NaN
40  2026-02-13     造纸  sz.002078    太阳纸业   NaN   NaN   NaN
41  2026-02-13     造纸  sh.600308    华泰股份   NaN   NaN   NaN
42  2026-02-13  液冷服务器  sh.688158   优刻得-W   NaN   NaN   NaN
43  2026-02-13  液冷服务器  sz.301018    申菱环境   NaN   NaN   NaN
44  2026-02-13  液冷服务器  bj.832662    方盛股份   NaN   NaN   NaN
45  2026-02-13  液冷服务器  sz.300249     依米康   NaN   NaN   NaN
46  2026-02-13  液冷服务器  sz.002131    利欧股份   NaN   NaN   NaN
47  2026-02-13  液冷服务器  sz.002272    川润股份   NaN   NaN   NaN
48  2026-02-13   冰雪旅游  sh.600706    曲江文旅   NaN   NaN   NaN
49  2026-02-13   冰雪旅游  sh.600138     中青旅   NaN   NaN   NaN
50  2026-02-13   冰雪旅游  sz.002159    三特索道   NaN   NaN   NaN
51  2026-02-13   冰雪旅游  sh.600054    黄山旅游   NaN   NaN   NaN
52  2026-02-13   冰雪旅游  sz.300144    宋城演艺   NaN   NaN   NaN
53  2026-02-13   冰雪旅游  sh.600258    首旅酒店   NaN   NaN   NaN
54  2026-02-13    机器人  sz.002896    中大力德   NaN   NaN   NaN
55  2026-02-13    机器人  sh.603728    鸣志电器   NaN   NaN   NaN
56  2026-02-13    机器人  sz.300124    汇川技术   NaN   NaN   NaN
57  2026-02-13    机器人  sh.688017    绿的谐波   NaN   NaN   NaN
58  2026-02-13    机器人  sz.002050    三花智控   NaN   NaN   NaN
59  2026-02-13    机器人  sh.688160    步科股份   NaN   NaN   NaN

                   创建时间
0   2026-02-13 17:29:19
1   2026-02-13 17:29:19
2   2026-02-13 17:29:19
3   2026-02-13 17:29:19
4   2026-02-13 17:29:19
5   2026-02-13 17:29:19
6   2026-02-13 17:29:19
7   2026-02-13 17:29:19
8   2026-02-13 17:29:19
9   2026-02-13 17:29:19
10  2026-02-13 17:29:19
11  2026-02-13 17:29:19
12  2026-02-13 17:29:19
13  2026-02-13 17:29:19
14  2026-02-13 17:29:19
15  2026-02-13 17:29:19
16  2026-02-13 17:29:19
17  2026-02-13 17:29:19
18  2026-02-13 17:29:19
19  2026-02-13 17:29:19
20  2026-02-13 17:29:19
21  2026-02-13 17:29:19
22  2026-02-13 17:29:19
23  2026-02-13 17:29:19
24  2026-02-13 17:29:19
25  2026-02-13 17:29:19
26  2026-02-13 17:29:19
27  2026-02-13 17:29:19
28  2026-02-13 17:29:19
29  2026-02-13 17:29:19
30  2026-02-13 17:29:19
31  2026-02-13 17:29:19
32  2026-02-13 17:29:19
33  2026-02-13 17:29:19
34  2026-02-13 17:29:19
35  2026-02-13 17:29:19
36  2026-02-13 17:29:19
37  2026-02-13 17:29:19
38  2026-02-13 17:29:19
39  2026-02-13 17:29:19
40  2026-02-13 17:29:19
41  2026-02-13 17:29:19
42  2026-02-13 17:29:19
43  2026-02-13 17:29:19
44  2026-02-13 17:29:19
45  2026-02-13 17:29:19
46  2026-02-13 17:29:19
47  2026-02-13 17:29:19
48  2026-02-13 17:29:19
49  2026-02-13 17:29:19
50  2026-02-13 17:29:19
51  2026-02-13 17:29:19
52  2026-02-13 17:29:19
53  2026-02-13 17:29:19
54  2026-02-13 17:29:19
55  2026-02-13 17:29:19
56  2026-02-13 17:29:19
57  2026-02-13 17:29:19
58  2026-02-13 17:29:19
59  2026-02-13 17:29:19

In [33]:
#导入股票池
import pandas as pd
from datetime import date

# 读取 GB2312 编码的 CSV 文件
df = pd.read_csv('/home/aiuser/work/我的文档/量化交易/股票池/自选股_20260422.csv', encoding='utf-8')
#print(df.head())


df.columns = [str(col).strip() for col in df.columns]

# 解析股票代码
stocks = []

# 定义后缀映射关系
suffix_map = {'SZ': '.SZ', 'SH': '.SH', 'BJ': '.BJ'}

for _, row in df.iterrows():
    code_raw = str(row.get('股票代码', '')).strip()
    name = str(row.get('股票名称', '')).strip()
    type = str(row.get('分类标签', '')).strip()
    # 清理代码中的空格和控制字符
    # 遍历映射关系，查找并替换
    for prefix, suffix in suffix_map.items():
        if code_raw.startswith(prefix):
            # 如果是前缀开头 (如 SZ300666)，去掉前缀并加上后缀
            code = code_raw[len(prefix):] + suffix
            #print(f"Matched prefix: {prefix}, code: {code}")
            break
        elif code_raw.isdigit():
        # 北交所代码规则判断：
        # 920开头 (最新号段)
        # 8 开头 (如 83, 87)
        # 4 开头 (如 430)
        # 92 开头 (部分老代码)
            if (code_raw.startswith('920') or 
                code_raw.startswith('8') or 
                code_raw.startswith('4') or 
                code_raw.startswith('92')):
                code = code_raw + '.BJ'
            else:
                code = code_raw 
        else:
            code = code_raw.upper()

    stocks.append({'code': code, 'name': name,'type': type})

print(len(stocks))
print(stocks)

import dai 
df = pd.DataFrame(stocks)
today = date.today()
df['date'] = today.strftime('%Y-%m-%d')
# 可选：定义分区，可以用于数据访问加速
df[dai.DEFAULT_PARTITION_FIELD] = df["date"]

dai.DataSource.write_bdb(
    data=df,
    # datasource id是全局唯一的，支持小写字母、数字、下划线，以字母开始
    id="stock_pool_wyc",
    # 数据插入时，根据unique_together如果有重复的，会去重.如果有分区,则需要传入索引参数indexes
    unique_together=["date", "code"],
    indexes=["date"],
)

816

dai.DataSource("stock_pool_wyc")

In [ ]:
import dai
from datetime import date, timedelta
#ds = dai.DataSource("stock_pool_wyc")

#ds.delete()
df = dai.query("SELECT * FROM stock_pool_wyc", full_db_scan=True).df()
yesterday = date.today() - timedelta(days=1)
day_str = yesterday.strftime('%Y-%m-%d')
df2 = dai.query("SELECT * FROM stock_pool_wyc WHERE date = '{}'".format(day_str)).df()
#print(df)
print(df2)

          code  name type        date
0    920002.BJ  万达轴承  自选股  2026-04-22
1    920021.BJ  流金科技  自选股  2026-04-22
2    920068.BJ  天工股份  自选股  2026-04-22
3    920077.BJ  吉林碳谷  自选股  2026-04-22
4    920179.BJ  凯德石英  自选股  2026-04-22
..         ...   ...  ...         ...
811  301439.SZ  泓淋电力  自选股  2026-04-22
812  301517.SZ  陕西华达  自选股  2026-04-22
813  301606.SZ  绿联科技  自选股  2026-04-22
814  301616.SZ  浙江华业  自选股  2026-04-22
815  301668.SZ  昊创瑞通  自选股  2026-04-22

[816 rows x 4 columns]

In [36]:
%%sql
/*
SELECT *
FROM cn_stock_instruments where date = '2026-04-21' 
*/
select * from stock_pool_wyc

┌───────────┬──────────┬─────────┬────────────┐
│   code    │   name   │  type   │    date    │
│  varchar  │ varchar  │ varchar │  varchar   │
├───────────┼──────────┼─────────┼────────────┤
│ 920002.BJ │ 万达轴承 │ 自选股  │ 2026-04-22 │
│ 920021.BJ │ 流金科技 │ 自选股  │ 2026-04-22 │
│ 920068.BJ │ 天工股份 │ 自选股  │ 2026-04-22 │
│ 920077.BJ │ 吉林碳谷 │ 自选股  │ 2026-04-22 │
│ 920179.BJ │ 凯德石英 │ 自选股  │ 2026-04-22 │
│ 920263.BJ │ 中航泰达 │ 自选股  │ 2026-04-22 │
│ 920371.BJ │ 欧福蛋业 │ 自选股  │ 2026-04-22 │
│ 920402.BJ │ 硅烷科技 │ 自选股  │ 2026-04-22 │
│ 920403.BJ │ 康农种业 │ 自选股  │ 2026-04-22 │
│ 920489.BJ │ 佳先股份 │ 自选股  │ 2026-04-22 │
│     ·     │    ·     │   ·     │     ·      │
│     ·     │    ·     │   ·     │     ·      │
│     ·     │    ·     │   ·     │     ·      │
│ 301379.SZ │ 天山电子 │ 自选股  │ 2026-04-22 │
│ 301381.SZ │ 赛维时代 │ 自选股  │ 2026-04-22 │
│ 301382.SZ │ 蜂助手   │ 自选股  │ 2026-04-22 │
│ 301396.SZ │ 宏景科技 │ 自选股  │ 2026-04-22 │
│ 301398.SZ │ 星源卓镁 │ 自选股  │ 2026-04-22 │
│ 301439.SZ │ 泓淋电力 │ 自选股  │ 2026-04-22 │
│ 301517.SZ │ 陕西华达 │ 自选股  │ 2026-04-22 │
│ 301606.SZ │ 绿联科技 │ 自选股  │ 2026-04-22 │
│ 301616.SZ │ 浙江华业 │ 自选股  │ 2026-04-22 │
│ 301668.SZ │ 昊创瑞通 │ 自选股  │ 2026-04-22 │
├───────────┴──────────┴─────────┴────────────┤
│ 816 rows (20 shown)               4 columns │
└─────────────────────────────────────────────┘

In [58]:
%%sql
-- 1. 先清理可能存在的旧临时表（防止重复创建报错）
DROP TABLE IF EXISTS temp_stock_base;
DROP TABLE IF EXISTS temp_stock_factor;
DROP TABLE IF EXISTS temp_stock_result;

-- 2. 第一步：获取基础数据
-- 筛选出时间范围内、符合状态要求的股票数据
CREATE TEMP TABLE temp_stock_base AS
SELECT 
    a.instrument,
    a.date,
    a.close,
    a.adjust_factor
FROM cn_stock_bar1d a
INNER JOIN cn_stock_status b ON a.instrument = b.instrument
WHERE a.date BETWEEN '2020-01-01' AND '2026-04-17' 
  AND b.st_status = 0 
  AND b.suspended = 0 
  AND b.is_risk_warning = 0 
  AND b.date = '2026-04-17';

-- 3. 第二步：计算关键因子
-- 为每只股票提取“最新日期”的复权因子，作为全量计算的基准
CREATE TEMP TABLE temp_stock_factor AS
SELECT 
    instrument,
    MAX(CASE WHEN date = '2026-04-17' THEN adjust_factor END) AS latest_factor
FROM temp_stock_base
GROUP BY instrument;

-- 4. 第三步：最终计算与输出
-- 关联因子表，计算前复权最高/最低，并格式化输出
CREATE TEMP TABLE temp_stock_result AS
SELECT 
    t1.instrument,
    -- 计算前复权最高/最低价：原始极值 / 最新因子
    MAX(t1.close) / t2.latest_factor AS max_close,
    MIN(t1.close) / t2.latest_factor AS min_close,
    -- 计算最新收盘价的前复权值
    MAX(CASE WHEN t1.date = '2026-04-17' THEN t1.close END) / t2.latest_factor AS latest_close
FROM temp_stock_base t1
JOIN temp_stock_factor t2 ON t1.instrument = t2.instrument
GROUP BY t1.instrument, t2.latest_factor;

-- 5. 查询最终结果
SELECT 
    instrument, 
    max_close, 
    min_close, 
    latest_close,
    ROUND(latest_close/ NULLIF(max_close, 0), 2) as ratio_pct,
    ROUND(latest_close/ NULLIF(min_close, 0), 2) as dpp
FROM temp_stock_result
where ratio_pct > 0.3
ORDER BY ratio_pct asc;

┌────────────┬────────────────────┬────────────────────┬──────────────┬───────────┬────────┐
│ instrument │     max_close      │     min_close      │ latest_close │ ratio_pct │  dpp   │
│  varchar   │       double       │       double       │    double    │  double   │ double │
├────────────┼────────────────────┼────────────────────┼──────────────┼───────────┼────────┤
│ 000009.SZ  │  28.61133767425139 │  5.686137378391111 │         8.98 │      0.31 │   1.58 │
│ 000652.SZ  │ 13.390741996926547 │  2.889458955223881 │         4.15 │      0.31 │   1.44 │
│ 002180.SZ  │ 57.702327050052844 │              16.11 │        17.77 │      0.31 │    1.1 │
│ 300027.SZ  │                6.8 │               1.46 │         2.09 │      0.31 │   1.43 │
│ 300369.SZ  │ 26.454827150531703 │               4.73 │         8.19 │      0.31 │   1.73 │
│ 300396.SZ  │  36.24498004040918 │              10.99 │        11.41 │      0.31 │   1.04 │
│ 300437.SZ  │ 50.986276661977534 │               6.45 │         16.0 │      0.31 │   2.48 │
│ 300612.SZ  │               48.7 │              10.08 │        15.12 │      0.31 │    1.5 │
│ 300745.SZ  │              87.79 │              12.81 │        27.16 │      0.31 │   2.12 │
│ 600132.SH  │  176.7700257567653 │ 34.529191649520726 │        53.97 │      0.31 │   1.56 │
│     ·      │                ·   │          ·         │          ·   │        ·  │     ·  │
│     ·      │                ·   │          ·         │          ·   │        ·  │     ·  │
│     ·      │                ·   │          ·         │          ·   │        ·  │     ·  │
│ 001400.SZ  │              193.6 │ 54.439470154258885 │        193.6 │       1.0 │   3.56 │
│ 688807.SH  │             363.19 │             185.87 │       363.19 │       1.0 │   1.95 │
│ 688809.SH  │              417.0 │             226.01 │        417.0 │       1.0 │   1.85 │
│ 920045.BJ  │              520.0 │             306.18 │        520.0 │       1.0 │    1.7 │
│ 688813.SH  │              76.36 │               42.0 │        76.36 │       1.0 │   1.82 │
│ 688811.SH  │              19.85 │              17.12 │        19.85 │       1.0 │   1.16 │
│ 920181.BJ  │              73.97 │              60.95 │        73.97 │       1.0 │   1.21 │
│ 920012.BJ  │              63.83 │               49.1 │        63.83 │       1.0 │    1.3 │
│ 920177.BJ  │               40.0 │              36.58 │         40.0 │       1.0 │   1.09 │
│ 301513.SZ  │              103.1 │              103.1 │        103.1 │       1.0 │    1.0 │
├────────────┴────────────────────┴────────────────────┴──────────────┴───────────┴────────┤
│ 5001 rows (20 shown)                                                           6 columns │
└──────────────────────────────────────────────────────────────────────────────────────────┘

In [59]:
# import pandas as pd
# 去除行数限制/列数限制
# pd.set_option('display.max_rows', 200)
# pd.set_option('display.max_columns', 200)
result = _.df()
result

     instrument   max_close   min_close  latest_close  ratio_pct   dpp
0     000009.SZ   28.611338    5.686137          8.98       0.31  1.58
1     000652.SZ   13.390742    2.889459          4.15       0.31  1.44
2     002180.SZ   57.702327   16.110000         17.77       0.31  1.10
3     300027.SZ    6.800000    1.460000          2.09       0.31  1.43
4     300369.SZ   26.454827    4.730000          8.19       0.31  1.73
...         ...         ...         ...           ...        ...   ...
4996  688811.SH   19.850000   17.120000         19.85       1.00  1.16
4997  920181.BJ   73.970000   60.950000         73.97       1.00  1.21
4998  920012.BJ   63.830000   49.100000         63.83       1.00  1.30
4999  920177.BJ   40.000000   36.580000         40.00       1.00  1.09
5000  301513.SZ  103.100000  103.100000        103.10       1.00  1.00

[5001 rows x 6 columns]

In [13]:
%%sql
/*
select *
from cn_stock_real_bar1d 
where instrument ='600000.SH'
and date = '2026-04-21'


select
a.instrument,
a.close,
a.sma_120
from cn_stock_prefactors a
where a.date = '2026-04-21' and a.instrument = '600000.SH'
*/
select * 
from cn_stock_factors_ta a
where a.date between '2025-04-21' and '2026-04-21'
and a.instrument = '600000.SH'
order by a.date desc

┌─────────────────────┬────────────┬────────────────────┬────────────────────┬────────────────────┬────────────────────┬────────────────────┬─────────┬────────────────────┬────────────────────┬────────────────────┬────────────────────┬────────────────────┬─────────┬────────────────────┬────────────────────┬────────────────────┬────────────────────┬────────────────────┬─────────┬─────────────────────┬─────────────────────┬─────────────────────┬─────────────────────┬──────────────────────┬─────────────────────┬──────────────────────┬─────────────────────┬──────────────────────┬─────────────────────┬──────────────────────┬──────────────────────┬────────────────────────┬────────────────────────┬───────────────────────┬───────────────────────┬──────────────────────┬──────────┬──────────────────────┬──────────────────────┬──────────────────────┬──────────────────────┬──────────────────────┬────────────────────┬────────────────────┬────────────────────┬────────────────────┬────────────────────┬────────────────────┬────────────────────┬────────────────────┬────────────────────┬────────────────────┬─────────────────────┬─────────────────────┬────────────────────┬─────────────────────┬──────────────────────┬────────────────────┬────────────────────┬────────────────────┬────────────────────┬────────────────────┬────────────────────┬─────────────────────┬──────────────────────┬──────────────────────┬────────────────────┬────────────────────┬────────────────────┬─────────────────────┬──────────────────────┬──────────────────────┬────────────────────┬─────────────────────┬─────────────────────┬────────────────────┬────────────────────┬────────────────────┬────────────────────┬─────────────────────┬─────────────────────┬────────────────────┬─────────────────────┬─────────────────────┬────────────────────┬────────────────────┬────────────────────┬────────────────────┬─────────────────────┬─────────────────────┬──────────────────────┬───────────────────────┬───────────────────────┬──────────────────────┬──────────────────────┬─────────────────────┬─────────────────────┬─────────────────────┬─────────────────────┬─────────────────────┬────────────────────┬──────────────┬─────────────────────┬─────────────────────┬───────────────┬─────────────────────┬─────────────────────┬────────────────────┬────────────────────┬────────────────────┬────────────────────┬────────────────────┐
│        date         │ instrument │       sma_5        │       sma_10       │       sma_20       │       sma_60       │      sma_120       │ sma_250 │       ema_5        │       ema_10       │       ema_20       │       ema_60       │      ema_120       │ ema_250 │       wma_5        │       wma_10       │       wma_20       │       wma_60       │      wma_120       │ wma_250 │  macd_diff_5_20_5   │  macd_diff_8_34_7   │  macd_diff_12_26_9  │ macd_diff_10_50_10  │   macd_dea_5_20_5    │   macd_dea_8_34_7   │   macd_dea_12_26_9   │  macd_dea_10_50_10  │   macd_hist_5_20_5   │  macd_hist_8_34_7   │  macd_hist_12_26_9   │  macd_hist_10_50_10  │         bias_5         │        bias_10         │        bias_20        │        bias_60        │       bias_120       │ bias_250 │    kdj_rsv_9_3_3     │    kdj_rsv_14_3_3    │    kdj_rsv_5_3_3     │    kdj_rsv_10_3_6    │    kdj_rsv_20_5_5    │    kdj_k_9_3_3     │    kdj_k_14_3_3    │    kdj_k_5_3_3     │    kdj_k_10_3_6    │    kdj_k_20_5_5    │    kdj_d_9_3_3     │    kdj_d_14_3_3    │    kdj_d_5_3_3     │    kdj_d_10_3_6    │    kdj_d_20_5_5    │     kdj_j_9_3_3     │    kdj_j_14_3_3     │    kdj_j_5_3_3     │    kdj_j_10_3_6     │     kdj_j_20_5_5     │       rsi_6        │       rsi_12       │       rsi_24       │       rsi_48       │       rsi_60       │      rsi_120       │ bbands_middle_5_1d5 │ bbands_middle_10_1d5 │ bbands_middle_20_1d5 │ bbands_middle_5_2  │ bbands_middle_10_2 │ bbands_middle_20_2 │ bbands_middle_5_2d5 │ bbands_middle_10_2d5 │ bbands_middle_20_2d5 │ bbands_upper_5_1d5 │ bbands_upper_10_1d5 │ bbands_upper_20_1d5 │  bbands_upper_5_2  │ bbands_upper_10_2  │ bbands_upper_20_2  │ bbands_upper_5_2d5 │ bbands_upper_10_2d5 │ bbands_upper_20_2d5 │ bbands_lower_5_1d5 │ bbands_lower_10_1d5 │ bbands_lower_20_1d5 │  bbands_lower_5_2  │ bbands_lower_10_2  │ bbands_lower_20_2  │ bbands_lower_5_2d5 │ bbands_lower_10_2d5 │ bbands_lower_20_2d5 │       trix_5_3       │       trix_7_4        │       trix_12_9       │      trix_20_12      │      trix_60_20      │        cci_5        │       cci_14        │       cci_20        │       cci_30        │       cci_60        │      cci_120       │     obv      │       maobv_6       │      maobv_14       │   maobv_20    │      maobv_30       │      maobv_60       │       atr_6        │       atr_14       │       atr_20       │       atr_30       │       atr_60       │
│    timestamp_ns     │  varchar   │       double       │       double       │       double       │       double       │       double       │ double  │       double       │       double       │       double       │       double       │       double       │ double  │       double       │       double       │       double       │       double       │       double       │ double  │       double        │       double        │       double        │       double        │        double        │       double        │        double        │       double        │        double        │       double        │        double        │        double        │         double         │         double         │        double         │        double         │        double        │  double  │        double        │        double        │        double        │        double        │        double        │       double       │       double       │       double       │       double       │       double       │       double       │       double       │       double       │       double       │       double       │       double        │       double        │       double       │       double        │        double        │       double       │       double       │       double       │       double       │       double       │       double       │       double        │        double        │        double        │       double       │       double       │       double       │       double        │        double        │        double        │       double       │       double        │       double        │       double       │       double       │       double       │       double       │       double        │       double        │       double       │       double        │       double        │       double       │       double       │       double       │       double       │       double        │       double        │        double        │        double         │        double         │        double        │        double        │       double        │       double        │       double        │       double        │       double        │       double       │    double    │       double        │       double        │    double     │       double        │       double        │       double       │       double       │       double       │       double       │       double       │
├─────────────────────┼────────────┼────────────────────┼────────────────────┼────────────────────┼────────────────────┼────────────────────┼─────────┼────────────────────┼────────────────────┼────────────────────┼────────────────────┼────────────────────┼─────────┼────────────────────┼────────────────────┼────────────────────┼────────────────────┼────────────────────┼─────────┼─────────────────────┼─────────────────────┼─────────────────────┼─────────────────────┼──────────────────────┼─────────────────────┼──────────────────────┼─────────────────────┼──────────────────────┼─────────────────────┼──────────────────────┼──────────────────────┼────────────────────────┼────────────────────────┼───────────────────────┼───────────────────────┼──────────────────────┼──────────┼──────────────────────┼──────────────────────┼──────────────────────┼──────────────────────┼──────────────────────┼────────────────────┼────────────────────┼────────────────────┼────────────────────┼────────────────────┼────────────────────┼────────────────────┼────────────────────┼────────────────────┼────────────────────┼─────────────────────┼─────────────────────┼────────────────────┼─────────────────────┼──────────────────────┼────────────────────┼────────────────────┼────────────────────┼────────────────────┼────────────────────┼────────────────────┼─────────────────────┼──────────────────────┼──────────────────────┼────────────────────┼────────────────────┼────────────────────┼─────────────────────┼──────────────────────┼──────────────────────┼────────────────────┼─────────────────────┼─────────────────────┼────────────────────┼────────────────────┼────────────────────┼────────────────────┼─────────────────────┼─────────────────────┼────────────────────┼─────────────────────┼─────────────────────┼────────────────────┼────────────────────┼────────────────────┼────────────────────┼─────────────────────┼─────────────────────┼──────────────────────┼───────────────────────┼───────────────────────┼──────────────────────┼──────────────────────┼─────────────────────┼─────────────────────┼─────────────────────┼─────────────────────┼─────────────────────┼────────────────────┼──────────────┼─────────────────────┼─────────────────────┼───────────────┼─────────────────────┼─────────────────────┼────────────────────┼────────────────────┼────────────────────┼────────────────────┼────────────────────┤
│ 2026-04-21 00:00:00 │ 600000.SH  │ 164.17300452500052 │ 164.75376611367827 │  166.1724837088762 │ 167.51100089420896 │ 180.73300639643315 │    NULL │  163.3071340025689 │  164.5083895430337 │ 165.63698046051468 │ 170.59914934341106 │ 179.21016677996812 │    NULL │  163.0667919751532 │ 164.14283509181897 │ 165.39141863349045 │  166.3523339213888 │ 173.61363726845548 │    NULL │ -2.3298464579457914 │  -2.818292189132194 │ -1.3221757996845156 │  -4.553811869447429 │  -1.5789295216914434 │  -2.101238766076666 │  -0.8629642821778882 │  -4.026677912225705 │   -1.501833872508696 │ -1.4341068461110558 │  -0.9184230350132547 │  -1.0542679144434484 │  -0.017586416009701344 │   -0.02104945110283015 │ -0.029407359328973506 │  -0.03716299879480269 │ -0.10760190965846553 │     NULL │ 0.042553191489362555 │ 0.029850746268657365 │ 0.042553191489362555 │ 0.042553191489362555 │ 0.029850746268657365 │ 16.397418869161385 │ 14.162727860878203 │ 21.467622415036647 │ 14.947492335479184 │  20.52777086423305 │ 25.582183606370627 │ 23.648818728716595 │  34.24949709406139 │ 29.769943948281515 │   34.1696302493209 │ -1.9721106052571002 │  -4.809453874798585 │ -4.096126943012834 │ -14.697410890125475 │   -6.755947905942648 │ 28.305665172151272 │ 36.752685821989964 │ 40.218870753714796 │ 41.555370940198415 │ 42.556781494328355 │ 47.223179431304764 │  164.17300452500052 │   164.75376611367827 │    166.1724837088762 │ 164.17300452500052 │ 164.75376611367827 │  166.1724837088762 │  164.17300452500052 │   164.75376611367827 │    166.1724837088762 │ 167.73354857307905 │  167.85541650786246 │  169.62353528389522 │ 168.92039658910522 │ 168.88929997259052 │ 170.77388580890155 │  170.1072446051314 │  169.92318343731858 │   171.9242363339079 │   160.612460476922 │  161.65211571949408 │  162.72143213385718 │ 159.42561246089582 │   160.618232254766 │ 161.57108160885085 │ 158.23876444486964 │  159.58434879003795 │   160.4207310838445 │  -0.1788474595452357 │  -0.12603831079415206 │ -0.028280528521976784 │  -0.0964067939840068 │ -0.18573400599146583 │  -94.13580246913611 │ -134.11458333333275 │  -173.5190468199355 │  -156.3408878889325 │ -109.58244969971372 │  -94.6893439777853 │ -469560476.0 │        -327074434.0 │  -270914335.4285714 │ -276554466.15 │        -262619654.0 │ -228726236.21666667 │ 2.6232267768439934 │  2.870958676518417 │   3.00792020676883 │ 3.2145615365042115 │ 3.7116763059655873 │
│ 2026-04-20 00:00:00 │ 600000.SH  │ 165.26815494936378 │ 165.18518900812438 │  166.2886360266117 │ 167.87605103566338 │  181.1907018389385 │    NULL │  164.3178061189227 │  165.2245228259609 │ 166.09500053321503 │  170.9148564475992 │ 179.51141681375142 │    NULL │ 164.39424703498742 │ 164.85181677150322 │ 165.86788018175238 │ 166.56840806125115 │  173.9426440795146 │    NULL │ -1.7771944142923246 │ -2.3509397731600075 │  -1.068278379058512 │  -4.155083143361878 │  -1.2034710535642694 │ -1.8622209583914902 │  -0.7481614028012314 │    -3.9095370328431 │  -1.1474467214561104 │ -0.9774376295370346 │   -0.640233952514561 │ -0.49109222103755634 │   -0.01807228915662504 │  -0.017579105976896034 │ -0.024098188893878728 │  -0.03332619475149492 │ -0.10436143015225005 │     NULL │                  0.0 │                  0.0 │                  0.0 │                  0.0 │                  0.0 │  22.46846872927395 │ 19.751554477884437 │ 30.073774048086843 │ 20.293578928750648 │ 24.913444923574882 │  30.17456597497525 │  28.39186416263579 │  40.64043443357376 │  32.73443427084198 │  37.58009509559287 │  7.0562742378713565 │   2.470935108381724 │  8.940453277113008 │  -4.588131755432016 │ -0.41985542046109003 │  31.67308938834104 │  38.79247479335169 │  41.26875314660807 │  42.03799489705875 │   42.9360079512804 │ 47.411795450030326 │  165.26815494936378 │   165.18518900812438 │    166.2886360266117 │ 165.26815494936378 │ 165.18518900812438 │  166.2886360266117 │  165.26815494936378 │   165.18518900812438 │    166.2886360266117 │  168.3083784438995 │  167.76521635463317 │  169.44019261514177 │ 169.32178627541143 │  168.6252254701361 │ 170.49071147798512 │ 170.33519410692332 │    169.485234585639 │  171.54123034082846 │ 162.22793145482805 │   162.6051616616156 │  163.13707943808163 │ 161.21452362331613 │ 161.74515254611268 │ 162.08656057523828 │ 160.20111579180423 │  160.88514343060976 │  161.03604171239493 │ -0.11898475962679826 │  -0.10947463689818804 │  -0.01720530941481608 │ -0.10084996269152076 │ -0.18557726411979392 │ -114.58333333333285 │ -128.42712842712672 │ -159.67454869056513 │ -131.92255740657376 │   -91.1017656286504 │ -91.17770242746546 │ -396711463.0 │  -302516116.8333333 │ -255869910.85714287 │  -270493979.7 │        -264855309.3 │       -213838716.05 │  2.583703731783238 │  2.874813805316159 │  3.017766428064675 │  3.228138072171675 │ 3.7267751924709738 │
│ 2026-04-17 00:00:00 │ 600000.SH  │ 165.53364596133062 │ 165.74935740855395 │  166.7034657328099 │ 168.25769436536575 │  181.6345696245706 │    NULL │  165.3360186460156 │  165.8785543284551 │  166.4964341614759 │  171.2075166300691 │ 179.80099724650796 │    NULL │ 165.47833533385202 │ 165.48235792492454 │ 166.28903110252122 │  166.7643527596324 │ 174.26253149372673 │    NULL │ -1.1604155154603006 │ -1.8970478996087365 │ -0.8300436448787138 │  -3.790775106360968 │  -0.9166093732002419 │ -1.6993146868019844 │  -0.6681321587369113 │ -3.8549712305055936 │  -0.4876122845201174 │ -0.3954664256135043 │   -0.323822972283605 │  0.12839224828925122 │  -0.011627906976742675 │  -0.012914205626188861 │  -0.01856367889314736 │ -0.027629394651633013 │ -0.09924175523006248 │     NULL │   0.2051282051282048 │   0.1355932203389831 │   0.2051282051282048 │  0.17021276595744658 │  0.11764705882352926 │  33.70270309391093 │ 29.627331716826653 │  45.11066107213026 │ 30.440368393125972 │ 31.141806154468604 │ 34.027614597825895 │  32.71201900501147 │  45.92376462631722 │  35.22260533926025 │  40.74675763859736 │   33.05288008608099 │   23.45795714045701 │  43.48445396375635 │  20.875894500857427 │   11.931903186211088 │  36.49751036049518 │  41.61540721476905 │ 42.692788029803545 │ 42.685218850901734 │ 43.443576758921324 │ 47.663513206418486 │  165.53364596133062 │   165.74935740855395 │    166.7034657328099 │ 165.53364596133062 │ 165.74935740855395 │  166.7034657328099 │  165.53364596133062 │   165.74935740855395 │    166.7034657328099 │ 168.04541842285744 │  168.14305062490573 │  169.83530364007873 │ 168.88267591003307 │ 168.94094836368964 │ 170.87924960916834 │ 169.71993339720868 │  169.73884610247356 │  171.92319557825795 │  163.0218734998038 │  163.35566419220217 │  163.57162782554104 │ 162.18461601262817 │ 162.55776645341825 │ 162.52768185645144 │ 161.34735852545256 │  161.75986871463434 │  161.48373588736183 │ -0.09984113965442927 │  -0.10878650081420638 │ -0.007552462968306164 │ -0.10645978193611878 │ -0.18535277094364255 │ -57.377049180328534 │  -96.54618473895526 │ -110.37998695832562 │   -91.7705454340354 │  -68.49632779281052 │ -86.07200884750335 │ -328594546.0 │  -282963930.3333333 │ -252927602.42857143 │  -263406218.7 │ -265624581.73333332 │ -198051824.08333334 │ 2.6690215836937536 │  2.930021446322736 │ 3.0630638994243604 │  3.265069920445503 │ 3.7533796114580977 │
│ 2026-04-16 00:00:00 │ 600000.SH  │  165.6332050908182 │ 166.39649175022316 │ 167.08510906251223 │  168.6393376950681 │ 182.06737528470404 │    NULL │ 166.19960990673778 │  166.3829361515404 │ 166.80039184957113 │ 171.46509902008597 │  180.0731344082212 │    NULL │ 166.15312498926772 │ 165.98920440231583 │ 166.62010471565847 │  166.9292872373536 │ 174.56763131455534 │    NULL │ -0.6007819428333505 │ -1.5440761738264541 │ -0.6490551917832192 │  -3.533760357163203 │  -0.7947063020702125 │ -1.6334036158664003 │  -0.6276542872014607 │  -3.869237035871066 │  0.38784871847372404 │ 0.17865488407989227 │ -0.04280180916351717 │   0.6709533574157263 │  0.0018032458425179965 │  -0.002792181890706221 │ -0.006902030885347341 │ -0.016054707358270956 │ -0.08862374590830104 │     NULL │   0.4680851063829772 │   0.3728813559322028 │   0.5641025641025621 │   0.3728813559322028 │  0.32352941176470484 │ 40.297644384456156 │  37.66133655829082 │  57.40958135178516 │  37.14991429181663 │ 35.986081222497525 │  34.19007034978338 │  34.25436264910388 │ 46.330316403410706 │   36.1790527284871 │ 43.147995509629546 │  52.512792453801694 │   44.47528437666469 │  79.56811124853405 │  39.091637418475685 │    21.66225264823349 │ 46.919941512617605 │  47.11544653493729 │  45.31518016790261 │   43.8418534085738 │ 44.345695155596815 │  48.10675147036682 │   165.6332050908182 │   166.39649175022316 │   167.08510906251223 │  165.6332050908182 │ 166.39649175022316 │ 167.08510906251223 │   165.6332050908182 │   166.39649175022316 │   167.08510906251223 │  167.9860466319912 │  169.22079667491857 │   170.3592982051432 │ 168.77032714571553 │ 170.16223164981704 │ 171.45069458602018 │ 169.55460765943988 │  171.10366662471554 │  172.54209096689718 │  163.2803635496452 │  163.57218682552775 │  163.81091991988126 │ 162.49608303592086 │ 162.63075185062928 │ 162.71952353900429 │  161.7118025221965 │  161.68931687573078 │  161.62812715812728 │ -0.13275720905654062 │  -0.11405913377987853 │  0.001090790534201247 │ -0.11306251318134519 │ -0.18505820617670643 │  62.770562770562854 │   -4.54431960049791 │ -19.019987105092895 │ -13.599176464214619 │  -31.38994507815844 │ -75.59844252581637 │ -270661509.0 │ -267654819.83333334 │ -252100262.57142857 │  -255980123.2 │        -271088618.8 │ -182245575.51666668 │ 2.7050302529946584 │ 2.9639478470253136 │  3.093278934278841 │ 3.2918317026267534 │ 3.7748101432253667 │